version: '3'

services:
  image-processor:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./store_master.json:/app/store_master.json
    environment:
      - PORT=8080
      - STORE_MASTER_PATH=/app/store_master.json